# Generated by Django 2.0.3 on 2018-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xpath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=1000)),
                ('major_url', models.CharField(max_length=1000)),
                ('relay_links', models.CharField(max_length=1000)),
                ('start_page_number', models.CharField(max_length=1000)),
                ('end_page_number', models.CharField(max_length=1000)),
                ('pagination_index', models.CharField(max_length=1000)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_seller', models.CharField(max_length=1000)),
                ('product_color', models.CharField(max_length=1000)),
                ('product_current_price', models.CharField(max_length=1000)),
                ('product_old_price', models.CharField(max_length=1000)),
                ('product_categories', models.CharField(max_length=1000)),
                ('product_sizes', models.CharField(max_length=1000)),
                ('product_percentage_off', models.CharField(max_length=1000)),
                ('product_images', models.CharField(max_length=1000)),
                ('product_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
