# Generated by Django 2.0.3 on 2018-04-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpaths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xpath',
            new_name='XpathList',
        ),
    ]
