# Generated by Django 2.0.3 on 2018-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpaths', '0002_auto_20180424_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathlist',
            name='product_url',
            field=models.CharField(default='http:localhost:8000', max_length=1000),
        ),
    ]
