# Generated by Django 2.0.3 on 2018-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpaths', '0004_auto_20180425_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathlist',
            name='product_filters',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
