# Generated by Django 2.0.3 on 2018-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpaths', '0005_xpathlist_product_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathlist',
            name='product_filters_texts',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
