# Generated by Django 2.0.3 on 2018-08-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180419_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='product_gender',
            field=models.CharField(default='U', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='product_images_urls',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='news',
            name='product_old_colors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='product_old_sizes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='product_store_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='product_sub_sub_categories',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_gender',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_urls',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_old_colors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_old_sizes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_store_name',
            field=models.CharField(default='U', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_sub_categories',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
