# Generated by Django 2.0.3 on 2018-08-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180803_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xpath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('major_url', models.CharField(max_length=1500)),
                ('relay_links', models.CharField(max_length=2500)),
                ('start_page_number', models.CharField(max_length=1500)),
                ('end_page_number', models.CharField(max_length=1500)),
                ('pagination_index', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=1500)),
                ('product_seller', models.CharField(max_length=1500)),
                ('product_color', models.CharField(max_length=1500)),
                ('product_current_price', models.CharField(max_length=1500)),
                ('product_old_price', models.CharField(max_length=1500)),
                ('product_categories', models.CharField(max_length=1500)),
                ('product_sizes', models.CharField(max_length=1500)),
                ('product_percentage_off', models.CharField(max_length=1500)),
                ('product_images', models.CharField(max_length=1500)),
                ('product_description', models.CharField(max_length=1500)),
                ('product_url', models.CharField(max_length=1500)),
            ],
        ),
    ]
