# Generated by Django 2.0.3 on 2018-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_xpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidentified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('product_seller', models.CharField(max_length=250)),
                ('product_old_price', models.CharField(max_length=250)),
                ('product_current_price', models.CharField(max_length=250)),
                ('product_url', models.CharField(max_length=1500)),
                ('product_categories', models.CharField(max_length=1500)),
                ('product_valid_sizes', models.CharField(max_length=500)),
                ('product_off', models.CharField(max_length=100)),
                ('product_valid_images', models.CharField(max_length=1500)),
                ('product_color', models.CharField(default=['Not Available in Colors'], max_length=500)),
                ('product_description', models.TextField(default='No Description Available')),
                ('product_sub_sub_categories', models.CharField(default='', max_length=1500)),
                ('product_store_name', models.CharField(default='U', max_length=250)),
                ('product_images_urls', models.CharField(default='', max_length=1500)),
                ('product_old_colors', models.CharField(default='', max_length=500)),
                ('product_old_sizes', models.CharField(default='', max_length=500)),
                ('product_gender', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
